auto: true
destination: kaylalewis.net
url: http://kaylalewis.net
markdown: kramdown
highlighter: true

paginate: 8

permalink: /:categories/:title

--- # Categories
- art
- transelemental
- cv
- rhino
- sketch

gems:
- jemoji
- jekyll-sitemap

sitemap:
  file: "/sitemap.xml"
  exclude:
    - "/im.html"
  include_posts:
    - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

prose:
  siteurl: 'http://kaylalewis.net'
  media: 'media'
  ignore: 
    - index.html
  metadata:
    _posts:
      - name: "category"
        field:
          element: "text"
          value: "blog"
      - name: "layout"
        field:
        label:"Layout"
          element: "hidden"
          value: "blog"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          placeholder: "Title Goes Here"
          value: ""
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          options:
            - name: "Apples"
              value: "apples"
            - name: "Bananas"
              value: "bananas"
            - name: "Pears"
              value: "pears"
            - name: "Mangos"
              value: "mangos"